### ISSUE TITLE
support new 280 char limit

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/monotweety#106]
https://github.com/twitter/twitter-text/pull/198
https://twittercommunity.com/t/updating-the-character-limit-and-the-twitter-text-library/96425

I'm planning to wait until they release twitter-text 2.0, but it seems to take some time 🤔

**Comment by hebertialmeida** [comment]
While there is no official one I have implemented a version in Swift https://gist.github.com/hebertialmeida/d868bd58efe8b5240e4ef8b542107099

**Comment by yshrsmz** [comment]
released as 1.6.0
