### ISSUE TITLE
New Icon/Logo Design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [yshrsmz/monotweety#110]
Hi @yshrsmz, Good day!  I am a graphic designer and i want to contribute to your project by proposing a new icon/logo design as i have noticed that the existing icon/logo in my opinion need to be updated. My proposed design aims to link it to the main feature of the app which is literally tweeting from the notifications area. If you like and want to use my design I will be very glad to send you the needed files as a gift for free. Just let me know.

here is the proposed design: 
![presentation](https://user-images.githubusercontent.com/36028424/39514396-9ac50958-4e29-11e8-8bd7-fc896db3e7d2.png)

Hoping for your positive feedback and best regards!

-tobaloidee

**Comment by yshrsmz** [comment]
Sorry for being late.
Thanks for your contribution. While your icon looks interesting, I love current icon, and I don't have any plan to replace it for now.

Thanks again!
